---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "blazorgke-config"
  namespace: "default"
  labels:
    app: "blazorgke"
data:
  ApiKey: "OIFJFJdfjdf874434x_x"
  BackendUrl: "https://localhost:7275"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "blazorgke"
  namespace: "default"
  labels:
    app: "blazorgke"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "blazorgke"
  template:
    metadata:
      labels:
        app: "blazorgke"
    spec:
      containers:
      - name: "blazorgke-sha256-1"
        image: "us-central1-docker.pkg.dev/firstgke-418008/gke-image-repository/blazorgke"
        env:
        - name: "ApiKey"
          valueFrom:
            configMapKeyRef:
              key: "ApiKey"
              name: "blazorgke-config"
        - name: "BackendUrl"
          valueFrom:
            configMapKeyRef:
              key: "BackendUrl"
              name: "blazorgke-config"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "blazorgke-hpa-aiew"
  namespace: "default"
  labels:
    app: "blazorgke"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "blazorgke"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
