---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "blazorgke"
  namespace: "default"
  labels:
    app: "blazorgke"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "blazorgke"
  template:
    metadata:
      labels:
        app: "blazorgke"
    spec:
      containers:
      - name: "blazorgke-sha256-1"
        image: "us-central1-docker.pkg.dev/firstgke-418008/gke-image-repository/blazorgke@sha256:380cb238e87d086de2a6efe91abe796fd256a9d49cbcaeb4b5dbaf4d11a5eeba"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "blazorgke-hpa-1gu9"
  namespace: "default"
  labels:
    app: "blazorgke"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "blazorgke"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blazorgke
  name: blazorgke-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30039
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: blazorgke
  sessionAffinity: None
  type: LoadBalancer