apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "webapp-config"
  namespace: "default"
  labels:
    app: "webapp"
data:
  ApiKey: "OIFJFJdfjdf874434x_x"
  BackendUrl: "http://localhost"
  ApiUrl: "http://blazorgke-api:8080"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webapp"
  namespace: "default"
  labels:
    app: "webapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "webapp"
  template:
    metadata:
      labels:
        app: "webapp"
    spec:
      serviceAccountName: default-webapp
      containers:
      - name: "webapp-sha256-1"
        image: "gcr.io/testblazorapp-417308/web-app:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: "ApiKey"
          valueFrom:
            configMapKeyRef:
              key: "ApiKey"
              name: "webapp-config"
        - name: "BackendUrl"
          valueFrom:
            configMapKeyRef:
              key: "BackendUrl"
              name: "webapp-config"
        - name: "ApiUrl"
          valueFrom:
            configMapKeyRef:
              key: "ApiUrl"
              name: "webapp-config"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: default-webapp
  labels:
    account: webapp
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: webapp
  labels:
    app: webapp
    service: webapp
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: webapp