apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "blazorgke-api-config"
  namespace: "default"
  labels:
    app: "blazorgke-api"
data:
  ApiKey: "OIFJFJdfjdf874434x_x"
  CORS: "http://webapp.default.svc.cluster.local:8080"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "blazorgke-api"
  namespace: "default"
  labels:
    app: "blazorgke-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "blazorgke-api"
  template:
    metadata:
      labels:
        app: "blazorgke-api"
    spec:
      containers:
      - name: "blazor-api-sha256-1"
        image: "gcr.io/testblazorapp-417308/blazor-api"
        imagePullPolicy: Always
        ports:
            - containerPort: 8080
        env:
        - name: "ApiKey"
          valueFrom:
            configMapKeyRef:
              key: "ApiKey"
              name: "blazorgke-api-config"
        - name: "CORS"
          valueFrom:
            configMapKeyRef:
              key: "CORS"
              name: "blazorgke-api-config"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: default-blazorgke-api
  labels:
    account: blazorgke-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: blazorgke-api
  annotations:
    istio.io/traffic-policy.mutual-tls: "true"  # Annotation to enable mTLS
  labels:
    app: blazorgke-api
    service: blazorgke-api
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: blazorgke-api