---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "webapp-config"
  namespace: "default"
  labels:
    app: "webapp"
data:
  ApiKey: "OIFJFJdfjdf874434x_x"
  BackendUrl: "http://localhost:7275"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webapp"
  namespace: "default"
  labels:
    app: "webapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "webapp"
  template:
    metadata:
      labels:
        app: "webapp"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "webapp"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: "webapp-sha256-1"
        image: "us-central1-docker.pkg.dev/firstgke-418008/gke-image-repository/webapp"
        env:
        - name: "ApiKey"
          valueFrom:
            configMapKeyRef:
              key: "ApiKey"
              name: "webapp-config"
        - name: "BackendUrl"
          valueFrom:
            configMapKeyRef:
              key: "BackendUrl"
              name: "webapp-config"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "webapp-hpa-aiew"
  namespace: "default"
  labels:
    app: "webapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "webapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
