---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "blazorgke-api-config"
  namespace: "default"
  labels:
    app: "blazorgke-api"
data:
  ApiKey: "OIFJFJdfjdf874434x_x"
  CORS: "http://webapp.default.svc.cluster.local"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "blazorgke-api"
  namespace: "default"
  labels:
    app: "blazorgke-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "blazorgke-api"
  template:
    metadata:
      labels:
        app: "blazorgke-api"
    spec:
      containers:
      - name: "blazorgke-api-sha256-1"
        image: "gcr.io/testblazorapp-417308/blazor-api:latest"
        ports:
            - containerPort: 8080
        env:
        - name: "ApiKey"
          valueFrom:
            configMapKeyRef:
              key: "ApiKey"
              name: "blazorgke-api-config"
        - name: "CORS"
          valueFrom:
            configMapKeyRef:
              key: "CORS"
              name: "blazorgke-api-config"
---

